'1.0.0':
  xmatch_plan: 1.0.0
  cartons:
    - hge_fardisk_core_apogee_sparse
    - hge_fardisk_core_apogee_extra
    - hge_dust_core_apogee
    - hge_gcs
    - hge_ocs
    - hge_ob
    - due_variables
    - due_rm
    - due_yso_disk_apogee_single
    - due_yso_disk_boss_single
    - due_yso_embedded_apogee_single
    - due_yso_nebula_apogee_single
    - due_yso_variable_apogee_single
    - due_yso_variable_boss_single
    - due_yso_cmz_apogee_single
    - due_yso_cluster_apogee_single
    - due_yso_cluster_boss_single
    - due_yso_pms_apogee_sagitta_edr3_single
    - due_yso_pms_apogee_zari18pms_single
    - due_yso_pms_boss_sagitta_edr3_single
    - due_yso_pms_boss_zari18pms_single
  open_fiber_path: /uufs/chpc.utah.edu/common/home/sdss50/sdsswork/target/open_fiber/postv1/draft2/
  schema: sandbox
  magnitudes:
    h: [catalog_to_twomass_psc, twomass_psc, twomass_psc.h_m]
    j: [catalog_to_twomass_psc, twomass_psc, twomass_psc.j_m]
    k: [catalog_to_twomass_psc, twomass_psc, twomass_psc.k_m]
    bp: [catalog_to_gaia_dr3_source, gaia_dr3_source, gaia_dr3_source.phot_bp_mean_mag]
    rp: [catalog_to_gaia_dr3_source, gaia_dr3_source, gaia_dr3_source.phot_rp_mean_mag]
    gaia_g: [catalog_to_gaia_dr3_source, gaia_dr3_source, gaia_dr3_source.phot_g_mean_mag]
  parameters:
    hge_dust_core_apogee:
      hge_galactic_core_dist_apogee_plan: 1.0.44
  database_options:
    work_mem: '10GB'
    enable_bitmapscan: false
    enable_seqscan: false
